"""
Tests for DOCXExporter._scrub_body() — the inverse of the old
``_add_footer``. The user requested removal of the "Generated by LDR..."
attribution paragraph from the report body, so we assert the scrubber
removes every variant of that line.

The footer-with-page-numbers lives separately (see TestDOCXPageNumberFooterXML
in test_docx_sanitize_metadata.py) because it is wired in by the DOCX
post-processor, not by a markdown scrub step.
"""

import pytest

from local_deep_research.exporters.docx_exporter import DOCXExporter


@pytest.fixture
def exporter():
    """Create a real DOCXExporter — no __init__ args needed."""
    return DOCXExporter()


class TestScrubBody:
    """Tests for _scrub_body(): removes the "Generated by LDR..." footer."""

    def test_ldr_footer_text_stripped(self, exporter):
        """The plain-text attribution line is removed."""
        result = exporter._scrub_body(
            "# Report\n\n正文\n\nGenerated by [LDR - Local Deep Research] | Open Source AI Research Assistant"
        )
        assert "Generated by" not in result
        assert "Local Deep Research" not in result
        # Original content survives.
        assert "正文" in result

    def test_italic_wrapped_ldr_footer_stripped(self, exporter):
        """The italic-marked variant (what _add_footer used to emit) is also removed."""
        result = exporter._scrub_body(
            "# Report\n\n正文\n\n*Generated by [LDR - Local Deep Research] | Open Source AI Research Assistant*"
        )
        assert "Generated by" not in result
        assert "*LDR" not in result

    def test_footer_with_leading_horizontal_rule_stripped(self, exporter):
        """The trailing ``---`` separator the ODT path added is also removed."""
        result = exporter._scrub_body(
            "# Report\n\n正文\n\n---\n\n*Generated by [LDR - Local Deep Research] | Open Source AI Research Assistant*"
        )
        assert "Generated by" not in result
        # No stray trailing --- line should survive.
        assert result.count("---") == 0

    def test_body_without_footer_unchanged(self, exporter):
        """Reports without the legacy footer come through untouched.

        ``_scrub_body`` is allowed to strip a trailing newline so the
        output never has a dangling blank line, but otherwise the body
        must be byte-identical to the input.
        """
        original = "# Report\n\n没有尾签"
        actual = exporter._scrub_body(original)
        # Body content is preserved.
        assert actual.rstrip("\n") == original.rstrip("\n")
        # No LDR attribution was added.
        assert "Local Deep Research" not in actual
        assert "Generated by" not in actual
