"""
Comprehensive tests for PDFService.
Tests PDF generation, markdown conversion, CSS handling, and metadata.
"""

import io
import subprocess

import pytest
from unittest.mock import patch


def _host_has_cjk_fonts() -> bool:
    """True if fontconfig reports any CJK-capable family on the host.

    Used to gate the strong glyph-embedding assertion in
    test_handles_cjk_content_embeds_glyphs: Docker CI (where this PR
    installs fonts-noto-cjk) and properly-configured dev hosts run the
    assertion; bare pip/macOS/Windows installs without Noto CJK skip it.
    """
    try:
        result = subprocess.run(
            ["fc-list", ":lang=zh"],
            capture_output=True,
            text=True,
            timeout=5,
        )
    except (FileNotFoundError, subprocess.TimeoutExpired):
        return False
    return bool(result.stdout.strip())


class TestPDFServiceInit:
    """Tests for PDFService initialization."""

    def test_init_creates_minimal_css(self):
        """Test that initialization creates minimal CSS."""
        from local_deep_research.web.services.pdf_service import PDFService

        service = PDFService()

        assert service.minimal_css is not None

    def test_minimal_css_includes_page_settings(self):
        """Test that minimal CSS includes @page settings."""
        from local_deep_research.web.services.pdf_service import PDFService

        service = PDFService()

        # The CSS object wraps the string, so we check it was created
        assert service.minimal_css is not None


class TestPDFServiceMarkdownToHtml:
    """Tests for _markdown_to_html method."""

    @pytest.fixture
    def service(self):
        """Create PDFService instance."""
        from local_deep_research.web.services.pdf_service import PDFService

        return PDFService()

    def test_converts_basic_markdown(self, service, simple_markdown):
        """Test conversion of basic markdown to HTML."""
        html = service._markdown_to_html(simple_markdown)

        # Markdown adds id attribute to headings
        assert "<h1" in html and "Hello World</h1>" in html
        assert "<p>This is a test.</p>" in html

    def test_includes_doctype_and_structure(self, service, simple_markdown):
        """Test that HTML includes proper structure."""
        html = service._markdown_to_html(simple_markdown)

        assert "<!DOCTYPE html>" in html
        assert "<html>" in html
        assert "</html>" in html
        assert "<head>" in html
        assert "</head>" in html
        assert "<body>" in html
        assert "</body>" in html

    def test_includes_charset_meta(self, service, simple_markdown):
        """Test that HTML includes UTF-8 charset."""
        html = service._markdown_to_html(simple_markdown)

        assert '<meta charset="utf-8">' in html

    def test_includes_title_when_provided(self, service, simple_markdown):
        """Test that title is included when provided."""
        html = service._markdown_to_html(simple_markdown, title="Test Title")

        assert "<title>Test Title</title>" in html

    def test_excludes_title_when_not_provided(self, service, simple_markdown):
        """Test that no title tag when title not provided."""
        html = service._markdown_to_html(simple_markdown)

        assert "<title>" not in html

    def test_includes_metadata_as_meta_tags(
        self, service, simple_markdown, sample_metadata
    ):
        """Test that metadata is included as meta tags."""
        html = service._markdown_to_html(
            simple_markdown, metadata=sample_metadata
        )

        assert '<meta name="author" content="Test Author">' in html
        assert '<meta name="date" content="2024-01-15">' in html
        assert '<meta name="subject" content="Test Subject">' in html

    def test_omits_ldr_attribution_footer(self, service, simple_markdown):
        """Test that LDR attribution footer is omitted.

        The "Generated by LDR..." line was removed per UX request — it is
        a third-party attribution that does not belong inside the report
        body itself, and it was the only consumer of the bottom of the
        page that competes with the page-number footer.
        """
        html = service._markdown_to_html(simple_markdown)

        assert "Generated by" not in html
        assert "Local Deep Research" not in html

    def test_inserts_title_div_when_query_provided(self, service, simple_markdown):
        """Test that a styled title div is inserted when query is provided.

        Format: "关于{query}的研究报告", 二号 (22pt) 黑体, centered.
        The class ldr-pdf-title is consumed by the minimal_css rule of
        the same name. Element is placed at the very top of <body>, i.e.
        before any TOC / chapter heading.
        """
        html = service._markdown_to_html(
            simple_markdown, query="人工智能的发展趋势"
        )

        assert 'class="ldr-pdf-title"' in html
        assert "关于人工智能的发展趋势的研究报告" in html
        # The title div must come before the first heading in the document.
        title_pos = html.index('class="ldr-pdf-title"')
        first_heading_pos = html.index("<h1")
        assert title_pos < first_heading_pos, (
            "ldr-pdf-title must precede the first heading so it sits before "
            "the TOC / chapter heading"
        )

    def test_no_title_div_when_query_missing(self, service, simple_markdown):
        """No title div is emitted when query is None / empty."""
        for q in (None, ""):
            html = service._markdown_to_html(simple_markdown, query=q)
            assert 'class="ldr-pdf-title"' not in html

    def test_title_escapes_html_in_query(self, service, simple_markdown):
        """Query text is HTML-escaped before insertion (defence in depth).

        ``html.escape`` escapes ``<``, ``>``, and ``&`` by default;
        passing ``quote=True`` (the default since Python 3.5) also
        escapes ``"`` to ``&quot;``. We assert the security-relevant
        transformations and the surrounding framing text, not the
        exact middle bytes — quote-escape is an implementation detail
        of ``html.escape`` and should not be coupled to.
        """
        html = service._markdown_to_html(
            simple_markdown, query='<script>alert("xss")</script>'
        )
        # The raw <script> tag must NOT survive into the HTML.
        assert "<script>" not in html
        assert "</script>" not in html
        # The angle brackets must be escaped — that is the security boundary.
        assert "&lt;script&gt;" in html
        assert "&lt;/script&gt;" in html
        # The framing "关于" + "的研究报告" must bracket the escaped query.
        assert html.index("关于") < html.index("&lt;script&gt;")
        assert html.index("&lt;/script&gt;") < html.index("的研究报告")

    def test_minimal_css_has_page_counter_footer(self):
        """The minimal CSS must declare an @page rule with a Chinese
        "第N页/共N页" footer at the bottom-centre, in 五号 (9pt) 宋体.
        WeasyPrint honours this for every page in the rendered PDF.
        """
        from local_deep_research.web.services.pdf_service import (
            PDFService,
            WEASYPRINT_AVAILABLE,
        )

        if not WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available in this environment")

        css_str = PDFService.MINIMAL_CSS_SOURCE

        assert "@page" in css_str
        assert "@bottom-center" in css_str
        assert "counter(page)" in css_str
        assert "counter(pages)" in css_str
        assert "第" in css_str and "页" in css_str and "共" in css_str
        # 五号 = 9pt; 宋体 family name must appear.
        assert "9pt" in css_str
        assert "SimSun" in css_str or "Songti" in css_str

    def test_minimal_css_has_title_rule(self):
        """The .ldr-pdf-title CSS rule must match the user's spec:
        黑体 family, 二号 (22pt), centered.
        """
        from local_deep_research.web.services.pdf_service import (
            PDFService,
            WEASYPRINT_AVAILABLE,
        )

        if not WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available in this environment")

        css_str = PDFService.MINIMAL_CSS_SOURCE

        assert ".ldr-pdf-title" in css_str
        assert "22pt" in css_str
        assert "text-align: center" in css_str
        # 黑体 family name must appear.
        assert (
            "SimHei" in css_str
            or "Heiti SC" in css_str
            or "Noto Sans CJK SC" in css_str
        )

    def test_converts_tables(self, service, sample_markdown):
        """Test that markdown tables are converted."""
        html = service._markdown_to_html(sample_markdown)

        assert "<table>" in html
        assert "<th>" in html
        assert "Column 1" in html

    def test_converts_code_blocks(self, service, sample_markdown):
        """Test that fenced code blocks are converted."""
        html = service._markdown_to_html(sample_markdown)

        assert "<code" in html or "<pre>" in html
        assert "def example():" in html

    def test_converts_lists(self, service, sample_markdown):
        """Test that lists are converted."""
        html = service._markdown_to_html(sample_markdown)

        assert "<li>" in html
        assert "Item 1" in html

    def test_converts_bold_and_italic(self, service, sample_markdown):
        """Test that bold and italic text are converted."""
        html = service._markdown_to_html(sample_markdown)

        assert "<strong>bold</strong>" in html
        assert "<em>italic</em>" in html

    def test_handles_special_characters(
        self, service, markdown_with_special_chars
    ):
        """Test handling of special characters."""
        html = service._markdown_to_html(markdown_with_special_chars)

        # Unicode should pass through
        assert "café" in html
        assert "naïve" in html
        assert "日本語" in html


class TestPDFServiceMarkdownToPdf:
    """Tests for markdown_to_pdf method."""

    @pytest.fixture
    def service(self):
        """Create PDFService instance."""
        from local_deep_research.web.services.pdf_service import PDFService

        return PDFService()

    def test_returns_bytes(self, service, simple_markdown):
        """Test that markdown_to_pdf returns bytes."""
        result = service.markdown_to_pdf(simple_markdown)

        assert isinstance(result, bytes)

    def test_returns_valid_pdf(self, service, simple_markdown):
        """Test that result is a valid PDF (starts with %PDF)."""
        result = service.markdown_to_pdf(simple_markdown)

        assert result.startswith(b"%PDF")

    def test_pdf_has_reasonable_size(self, service, simple_markdown):
        """Test that generated PDF has a reasonable size."""
        result = service.markdown_to_pdf(simple_markdown)

        # A simple PDF should be at least a few KB
        assert len(result) > 1000

    def test_applies_title(self, service, simple_markdown):
        """Test that title is applied to PDF."""
        result = service.markdown_to_pdf(simple_markdown, title="My Title")

        # PDF was generated successfully
        assert result.startswith(b"%PDF")
        assert len(result) > 0

    def test_applies_metadata(self, service, simple_markdown, sample_metadata):
        """Test that metadata is applied to PDF."""
        result = service.markdown_to_pdf(
            simple_markdown, metadata=sample_metadata
        )

        assert result.startswith(b"%PDF")

    def test_applies_custom_css(self, service, simple_markdown, custom_css):
        """Test that custom CSS is applied."""
        result = service.markdown_to_pdf(simple_markdown, custom_css=custom_css)

        assert result.startswith(b"%PDF")

    def test_uses_minimal_css_when_no_custom_css(
        self, service, simple_markdown
    ):
        """Test that minimal CSS is used by default."""
        result = service.markdown_to_pdf(simple_markdown)

        assert result.startswith(b"%PDF")

    def test_handles_empty_markdown(self, service):
        """Test handling of empty markdown."""
        result = service.markdown_to_pdf("")

        assert result.startswith(b"%PDF")

    def test_handles_large_markdown(self, service):
        """Test handling of large markdown content."""
        # Create a large markdown document
        large_content = "# Large Document\n\n"
        large_content += ("This is a paragraph. " * 100 + "\n\n") * 50

        result = service.markdown_to_pdf(large_content)

        assert result.startswith(b"%PDF")
        # Large content should produce larger PDF
        assert len(result) > 10000

    def test_handles_markdown_with_all_features(self, service, sample_markdown):
        """Test handling of markdown with tables, code, lists."""
        result = service.markdown_to_pdf(sample_markdown)

        assert result.startswith(b"%PDF")

    def test_handles_cjk_content(self, service):
        """Regression guard for #4055 — CJK text must not crash export.

        Glyph visibility depends on the host having CJK fonts installed
        (e.g. fonts-noto-cjk). This test pins the no-crash contract; the
        glyph-embedding contract is checked separately in
        test_handles_cjk_content_embeds_glyphs.
        """
        cjk_markdown = (
            "# 中文标题\n\n这是一个测试。\n\n"
            "## 日本語の見出し\n\nテスト本文。\n\n"
            "## 한국어 제목\n\n본문 테스트.\n"
        )

        result = service.markdown_to_pdf(cjk_markdown)

        assert result.startswith(b"%PDF")
        assert len(result) > 1000

    @pytest.mark.skipif(
        not _host_has_cjk_fonts(),
        reason="no CJK fonts on host; install fonts-noto-cjk to run",
    )
    def test_handles_cjk_content_embeds_glyphs(self, service):
        """End-to-end glyph check for #4055.

        Round-trips CJK text through markdown → PDF → text extraction.
        If no CJK-capable font is available to WeasyPrint, glyphs are
        dropped and pypdf's extract_text returns the rendered text
        without them.

        What this catches: removal of fonts-noto-cjk from the runtime
        Docker image (the load-bearing half of the fix) — pytest-tests
        runs inside that image, so the test fails when fonts are gone.

        What this does NOT catch: removal of the CSS CJK fallback list.
        On Linux, fontconfig auto-substitutes a glyph-bearing family
        even for a Latin-only CSS stack, so the assertion still passes.
        The CSS fallbacks matter on Windows/macOS, which CI doesn't run.
        """
        import pypdf

        cjk_markdown = (
            "# 中文标题\n\n这是一个测试。\n\n"
            "## 日本語の見出し\n\nテスト本文。\n\n"
            "## 한국어 제목\n\n본문 테스트.\n"
        )

        pdf_bytes = service.markdown_to_pdf(cjk_markdown)
        reader = pypdf.PdfReader(io.BytesIO(pdf_bytes))
        extracted = "".join(page.extract_text() for page in reader.pages)

        for phrase in (
            "中文标题",
            "这是一个测试",
            "日本語",
            "テスト",
            "한국어",
            "본문",
        ):
            assert phrase in extracted, (
                f"CJK glyphs missing from PDF: {phrase!r} not found in "
                f"extracted text — WeasyPrint could not match a glyph "
                f"(check that fonts-noto-cjk is installed on the host)"
            )

    def test_logs_pdf_size(self, service, simple_markdown):
        """Test that PDF size is logged."""
        with patch(
            "local_deep_research.web.services.pdf_service.logger"
        ) as mock_logger:
            service.markdown_to_pdf(simple_markdown)

            mock_logger.info.assert_called_once()
            call_args = mock_logger.info.call_args[0][0]
            assert "Generated PDF" in call_args
            assert "bytes" in call_args


class TestPDFServiceErrorHandling:
    """Tests for error handling in PDFService."""

    @pytest.fixture
    def service(self):
        """Create PDFService instance."""
        from local_deep_research.web.services.pdf_service import PDFService

        return PDFService()

    def test_raises_exception_on_html_error(self, service):
        """Test that exceptions are raised on HTML conversion errors."""
        with patch.object(
            service, "_markdown_to_html", side_effect=Exception("HTML error")
        ):
            with pytest.raises(Exception) as exc_info:
                service.markdown_to_pdf("test")

            assert "HTML error" in str(exc_info.value)

    def test_logs_exception_on_error(self, service):
        """Test that exceptions are logged."""
        with patch.object(
            service, "_markdown_to_html", side_effect=Exception("Test error")
        ):
            with patch(
                "local_deep_research.web.services.pdf_service.logger"
            ) as mock_logger:
                with pytest.raises(Exception):
                    service.markdown_to_pdf("test")

                mock_logger.exception.assert_called_once()


class TestPDFServiceSingleton:
    """Tests for get_pdf_service singleton."""

    def test_get_pdf_service_returns_instance(self):
        """Test that get_pdf_service returns a PDFService instance."""
        from local_deep_research.web.services.pdf_service import (
            get_pdf_service,
            PDFService,
        )

        service = get_pdf_service()

        assert isinstance(service, PDFService)

    def test_get_pdf_service_returns_same_instance(self):
        """Test that get_pdf_service returns the same instance."""
        from local_deep_research.web.services.pdf_service import (
            get_pdf_service,
        )

        service1 = get_pdf_service()
        service2 = get_pdf_service()

        assert service1 is service2

    def test_singleton_can_be_reset(self):
        """Test that singleton can be reset for testing."""
        import local_deep_research.web.services.pdf_service as pdf_module

        # Reset singleton
        pdf_module._pdf_service = None

        service1 = pdf_module.get_pdf_service()

        # Reset again
        pdf_module._pdf_service = None

        service2 = pdf_module.get_pdf_service()

        # Different instances after reset
        assert service1 is not service2


class TestPDFServiceUrlFetcher:
    """Tests for the SSRF-safe + timeout-bounded + image-fallback
    url_fetcher wired into WeasyPrint.

    Without this layer, a single slow or unreachable CDN image would
    freeze the entire PDF render. The client-side loadImageForPdf helper
    carries the equivalent contract; this class is its server-side twin.
    """

    @pytest.fixture
    def module(self):
        from local_deep_research.web.services import pdf_service
        return pdf_service

    def test_image_url_returns_placeholder_on_timeout(self, module, monkeypatch):
        """Image fetch that exceeds the 5 s budget must return a tiny
        PNG placeholder so WeasyPrint embeds *something* (an invisible
        1×1) rather than logging an error and leaving a missing-image
        gap in the PDF.
        """
        if not module.WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available")

        import concurrent.futures

        class HangingFetcher:
            def fetch(self, url):
                # Simulate an image CDN that never responds.
                raise concurrent.futures.TimeoutError()

        monkeypatch.setattr(module, "_URL_FETCHER", HangingFetcher())

        result = module._safe_url_fetcher(
            "https://1.1.1.1/figure.png"
        )

        # WeasyPrint's url_fetcher contract: a mapping with `string` (bytes)
        # and `mime_type`. A placeholder image must satisfy that shape.
        assert isinstance(result, dict)
        assert result["mime_type"] == "image/png"
        assert isinstance(result["string"], (bytes, bytearray))
        assert len(result["string"]) > 0

    def test_image_url_returns_placeholder_on_fetch_error(
        self, module, monkeypatch
    ):
        """Network / DNS / 5xx errors on image URLs also fall back to
        a placeholder, matching the client-side helper's contract.
        """
        if not module.WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available")

        class BrokenFetcher:
            def fetch(self, url):
                raise OSError("DNS failure")

        monkeypatch.setattr(module, "_URL_FETCHER", BrokenFetcher())

        result = module._safe_url_fetcher(
            "https://1.1.1.1/x.jpg"
        )
        assert result["mime_type"] == "image/png"
        assert len(result["string"]) > 0

    def test_non_image_url_propagates_failure(self, module, monkeypatch):
        """Non-image resources (CSS / JS) must NOT silently substitute a
        placeholder — that would mask real bundling / configuration bugs.
        Failure re-raises so WeasyPrint logs the missing resource.
        """
        if not module.WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available")

        class BrokenFetcher:
            def fetch(self, url):
                raise OSError("upstream 503")

        monkeypatch.setattr(module, "_URL_FETCHER", BrokenFetcher())

        with pytest.raises(OSError):
            module._safe_url_fetcher(
                "https://1.1.1.1/theme.css"
            )

    def test_successful_image_fetch_passes_through(self, module, monkeypatch):
        """Happy path: real fetched bytes must be returned verbatim —
        not wrapped in a placeholder. Parity with client-side helper
        which returns {dataUrl, width, height, format} on success.
        """
        if not module.WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available")

        sentinel = {
            "string": b"\x89PNG\r\n\x1a\nREAL_IMAGE",
            "mime_type": "image/png",
        }

        class PassThroughFetcher:
            def fetch(self, url):
                return sentinel

        monkeypatch.setattr(module, "_URL_FETCHER", PassThroughFetcher())

        result = module._safe_url_fetcher("https://1.1.1.1/x.png")
        assert result is sentinel

    def test_unsafe_url_still_blocked(self, module, monkeypatch):
        """SSRF guard is preserved: metadata IPs / private nets / unsafe
        schemes still raise UnsafePDFResourceURLError before the timeout
        branch can mask them.
        """
        from local_deep_research.web.services.pdf_service import (
            UnsafePDFResourceURLError,
        )

        called = {"v": False}

        class SpyFetcher:
            def fetch(self, url):
                called["v"] = True
                return {}

        monkeypatch.setattr(module, "_URL_FETCHER", SpyFetcher())

        with pytest.raises(UnsafePDFResourceURLError):
            module._safe_url_fetcher("http://169.254.169.254/latest/meta-data")
        assert called["v"] is False, "fetcher must not be reached for unsafe URLs"


class TestPDFServiceQueryParam:
    """The new `query` keyword argument threaded through markdown_to_pdf
    and _markdown_to_html. PDFExporter overrides _prepend_title_if_needed
    to no-op so the custom title doesn't compete with an H1.
    """

    @pytest.fixture
    def service(self):
        from local_deep_research.web.services.pdf_service import PDFService
        return PDFService()

    def test_markdown_to_pdf_accepts_query_kwarg(self, service, simple_markdown):
        """End-to-end: query is forwarded to the HTML layer without
        breaking the PDF render path. (Full glyph-embedding assertion
        lives in test_handles_cjk_content_embeds_glyphs.)
        """
        from local_deep_research.web.services.pdf_service import WEASYPRINT_AVAILABLE

        if not WEASYPRINT_AVAILABLE:
            pytest.skip("WeasyPrint not available in this environment")

        result = service.markdown_to_pdf(
            simple_markdown, query="量子计算简介"
        )
        assert isinstance(result, bytes)
        assert result[:4] == b"%PDF"

    def test_query_kwarg_is_in_signature(self, service):
        """API contract: ``query`` is a public keyword argument on
        ``markdown_to_pdf`` so downstream callers (PDFExporter /
        export_research_report) can pass the original research query
        without TypeError. This guards against a silent signature
        rename breaking the export pipeline.
        """
        import inspect

        sig = inspect.signature(service.markdown_to_pdf)
        params = sig.parameters
        assert "query" in params, (
            f"markdown_to_pdf must accept a `query` kwarg; got params: "
            f"{list(params)}"
        )
        # Optional default — must be None when not supplied.
        assert params["query"].default is None
