"""DOCX (Microsoft Word) export service using pypandoc.

This module produces real ``.docx`` files (Office Open XML) via Pandoc,
which natively handles every markdown feature the reports carry —
including the rewritten ``<figure class="ldr-img"><img src="/images/...">``
blocks that ``images.store.rewrite_markdown`` injects. After Pandoc
writes the base DOCX we post-process the zip to add a Chinese
"第X页/共X页" page-number footer via OOXML field codes — Pandoc
itself has no built-in switch for that pattern.
"""

import io
import re
import subprocess
import zipfile
from typing import Optional

from loguru import logger

# pypandoc is optional - used only to locate the bundled pandoc binary
try:
    import pypandoc

    PYPANDOC_AVAILABLE = True
except ImportError:
    pypandoc = None
    PYPANDOC_AVAILABLE = False

from .base import BaseExporter, ExportOptions, ExportResult
from .registry import ExporterRegistry


# OOXML namespaces — used in the footer XML below. Centralised so the
# injected XML stays consistent with what Word/LibreOffice produces.
_W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


@ExporterRegistry.register
class DOCXExporter(BaseExporter):
    """Service for converting markdown to DOCX (Microsoft Word).

    Uses Pandoc (via pypandoc) for the markdown → DOCX conversion and
    then post-processes the zip to inject:

    * A centred Chinese page-number footer ("第X页/共X页") with PAGE /
      NUMPAGES as real OOXML field codes — Word/LibreOffice updates the
      numbers automatically when the document is opened.

    The exporter threads ``query`` (for the title heading) and
    ``base_url`` (for resolving the rewritten local image routes) the
    same way the PDF path does — so a single research report produces a
    consistent title and embedded images regardless of format.

    The old "Generated by LDR..." body footer is intentionally not
    re-added: the request was to remove that third-party attribution
    from inside the report body. The page-number footer that replaces
    it carries the project link in the same way the PDF footer does.
    """

    @property
    def format_name(self) -> str:
        return "docx"

    @property
    def file_extension(self) -> str:
        return ".docx"

    @property
    def mimetype(self) -> str:
        return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    # ------------------------------------------------------------------
    # Title / footer pre-processing
    # ------------------------------------------------------------------

    @staticmethod
    def _prepend_title(markdown_content: str, query: Optional[str]) -> str:
        """Prepend the "关于{query}的研究报告" title heading.

        Returned markdown starts with an H1 so Pandoc's DOCX writer
        produces a Title-style paragraph at the very top of the body —
        before any TOC / chapter heading that the report carries.
        Returns the input unchanged when no query is provided.
        """
        if not query:
            return markdown_content
        return f"# 关于{query}的研究报告\n\n{markdown_content}"

    @staticmethod
    def _scrub_body(markdown_content: str) -> str:
        """Strip the old LDR attribution footer from the body, if any.

        ``ODTExporter._add_footer`` used to append ``Generated by LDR...``
        to every export. The request was to remove that text from the
        report body. We scrub defensively so that any historical
        markdown already containing the footer still comes out clean.
        """
        # Strip the "Generated by [LDR ...]" attribution paragraph,
        # whether or not it is wrapped in italic ``*...*`` markers, and
        # drop the ``---`` horizontal rule that may have preceded it.
        # Match across the full paragraph so we leave no stray blank
        # lines behind.
        pattern = re.compile(
            r"(?:\s*---\s*\n)?\s*\*?Generated by "
            r"\[LDR[^\]]*\][^\n]*\*?\s*$",
            re.MULTILINE,
        )
        return pattern.sub("", markdown_content).rstrip() + "\n"

    # ------------------------------------------------------------------
    # Page-number footer XML
    # ------------------------------------------------------------------

    @staticmethod
    def _build_footer_xml() -> str:
        """Return the inner XML of word/footer1.xml carrying the
        Chinese page-number footer. Uses real OOXML field codes for
        PAGE / NUMPAGES so Word updates them on open.

        Mirrors the PDF path's "第X页/共X页" format and font stack
        (宋体 family, 五号 ≈ 9pt) so DOCX and PDF exports look
        consistent. Centred.
        """
        # We embed the field codes directly (fldSimple) so Word treats
        # them as live PAGE / NUMPAGES fields rather than literal text.
        return (
            '<w:p>'
            '<w:pPr>'
            '<w:jc w:val="center"/>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'   # 9pt = 18 half-points (五号)
            '<w:szCs w:val="18"/>'
            '<w:color w:val="666666"/>'
            '</w:rPr>'
            '</w:pPr>'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            '<w:color w:val="666666"/>'
            '</w:rPr>'
            '<w:t xml:space="preserve">第</w:t>'
            '</w:r>'
            '<w:fldSimple w:instr="PAGE \\* MERGEFORMAT">'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            '<w:color w:val="666666"/>'
            '</w:rPr>'
            '<w:t>1</w:t>'
            '</w:r>'
            '</w:fldSimple>'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            '<w:color w:val="666666"/>'
            '</w:rPr>'
            '<w:t xml:space="preserve">页/共</w:t>'
            '</w:r>'
            '<w:fldSimple w:instr="NUMPAGES \\* MERGEFORMAT">'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            '<w:color w:val="666666"/>'
            '</w:rPr>'
            '<w:t>1</w:t>'
            '</w:r>'
            '</w:fldSimple>'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            '<w:color w:val="666666"/>'
            '</w:rPr>'
            '<w:t xml:space="preserve">页</w:t>'
            '</w:r>'
            '</w:p>'
        )

    @staticmethod
    def _wrap_footer(footer_inner_xml: str) -> str:
        """Wrap the footer inner XML in the required ``<w:ftr>`` root."""
        return (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            f'<w:ftr xmlns:w="{_W_NS}">'
            f'{footer_inner_xml}'
            '</w:ftr>'
        )

    @classmethod
    def _inject_footer_into_docx(cls, docx_bytes: bytes) -> bytes:
        """Return a copy of the DOCX with the Chinese page-number
        footer wired into every section's default footer reference.

        Algorithm:
          1. Unzip the DOCX into memory.
          2. If ``word/footer1.xml`` doesn't exist, create it with
             our page-number XML.
          3. Ensure ``word/_rels/document.xml.rels`` carries a
             relationship to ``footer1.xml`` with a stable Id.
          4. Ensure ``[Content_Types].xml`` declares the footer part.
          5. Ensure each ``<w:sectPr>`` in ``word/document.xml``
             references the footer relationship.

        Idempotent: re-running on an already-patched DOCX keeps the
        existing footer instead of duplicating it.
        """
        if not docx_bytes:
            return docx_bytes

        footer_xml = cls._wrap_footer(cls._build_footer_xml())
        footer_rid = "rIdLdrFooter"

        # Read everything into memory up front — DOCX files are small.
        src_zip = zipfile.ZipFile(io.BytesIO(docx_bytes), "r")
        names_to_data = {name: src_zip.read(name) for name in src_zip.namelist()}
        src_zip.close()

        # 1) Write footer1.xml (overwrite if present, create if not).
        names_to_data["word/footer1.xml"] = footer_xml.encode("utf-8")

        # 2) Update word/_rels/document.xml.rels so the footer part is
        #    discoverable by document.xml.
        rels_path = "word/_rels/document.xml.rels"
        rels_xml = names_to_data.get(rels_path, b"").decode("utf-8") if rels_path in names_to_data else ""
        if rels_xml and 'Target="footer1.xml"' not in rels_xml:
            # Insert the footer relationship before </Relationships>.
            new_rel = (
                f'<Relationship Id="{footer_rid}" '
                'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" '
                'Target="footer1.xml"/>'
            )
            rels_xml = rels_xml.replace(
                "</Relationships>", new_rel + "</Relationships>", 1
            )
            names_to_data[rels_path] = rels_xml.encode("utf-8")
        elif not rels_xml:
            # No rels file at all — minimal valid one.
            rels_xml = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
                + f'<Relationship Id="{footer_rid}" '
                'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" '
                'Target="footer1.xml"/>'
                + "</Relationships>"
            )
            names_to_data[rels_path] = rels_xml.encode("utf-8")

        # 3) Update [Content_Types].xml so the footer part is declared.
        ct_path = "[Content_Types].xml"
        ct_xml = (
            names_to_data[ct_path].decode("utf-8")
            if ct_path in names_to_data
            else ""
        )
        if ct_xml and 'PartName="/word/footer1.xml"' not in ct_xml:
            override = (
                '<Override PartName="/word/footer1.xml" '
                'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>'
            )
            ct_xml = ct_xml.replace("</Types>", override + "</Types>", 1)
            names_to_data[ct_path] = ct_xml.encode("utf-8")
        elif not ct_xml:
            ct_xml = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
                '<Default Extension="xml" ContentType="application/xml"/>'
                '<Override PartName="/word/document.xml" '
                'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
                '<Override PartName="/word/footer1.xml" '
                'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>'
                '</Types>'
            )
            names_to_data[ct_path] = ct_xml.encode("utf-8")

        # 4) Update every <w:sectPr> in word/document.xml to reference
        #    our footer relationship. Word renders the footer on every
        #    page in the section.
        doc_path = "word/document.xml"
        doc_xml = (
            names_to_data[doc_path].decode("utf-8")
            if doc_path in names_to_data
            else ""
        )
        if doc_xml and f'r:id="{footer_rid}"' not in doc_xml:
            # Find every <w:sectPr ...> ... </w:sectPr> block and
            # ensure it carries a <w:footerReference w:type="default"
            # r:id="..."/> child. If the block already has one, replace
            # the r:id. Otherwise insert one as the first child.
            def patch_sectpr(match: "re.Match[str]") -> str:
                block = match.group(0)
                if "footerReference" in block and f'r:id="{footer_rid}"' in block:
                    return block
                new_ref = (
                    f'<w:footerReference w:type="default" r:id="{footer_rid}"/>'
                )
                if "footerReference" in block:
                    # Replace the first existing footerReference's r:id.
                    return re.sub(
                        r'<w:footerReference[^/]*r:id="[^"]*"[^/]*/>',
                        new_ref,
                        block,
                        count=1,
                    )
                # Insert as the first child of sectPr.
                # Find the opening tag's closing >.
                open_tag_end = block.find(">") + 1
                return block[:open_tag_end] + new_ref + block[open_tag_end:]

            doc_xml = re.sub(
                r"<w:sectPr\b[^>]*>.*?</w:sectPr>",
                patch_sectpr,
                doc_xml,
                flags=re.DOTALL,
            )
            # Self-closing <w:sectPr .../> form (Pandoc occasionally emits
            # this for the final section).
            def patch_selfclosing_sectpr(match: "re.Match[str]") -> str:
                attrs = match.group(1)
                return (
                    f"<w:sectPr{attrs}>"
                    f'<w:footerReference w:type="default" r:id="{footer_rid}"/>'
                    "</w:sectPr>"
                )
            doc_xml = re.sub(
                r"<w:sectPr\b([^>]*)/>",
                patch_selfclosing_sectpr,
                doc_xml,
            )
            names_to_data[doc_path] = doc_xml.encode("utf-8")

        # Write the new zip back out.
        out_buf = io.BytesIO()
        with zipfile.ZipFile(out_buf, "w", zipfile.ZIP_DEFLATED) as dst_zip:
            for name, data in names_to_data.items():
                dst_zip.writestr(name, data)
        return out_buf.getvalue()

    # ------------------------------------------------------------------
    # Markdown → DOCX
    # ------------------------------------------------------------------

    def export(
        self,
        markdown_content: str,
        options: Optional[ExportOptions] = None,
    ) -> ExportResult:
        """Convert markdown content to DOCX.

        Flow:
          1. Prepend the "关于{query}的研究报告" title (if query given).
          2. Scrub the old "Generated by LDR..." body footer.
          3. Run Pandoc markdown → DOCX, with ``--resource-path`` set to
             the request's base_url so the rewritten
             ``/images/<research_id>/<filename>`` routes resolve.
          4. Post-process the resulting DOCX zip to inject the
             Chinese page-number footer.

        Args:
            markdown_content: The markdown text to convert
            options: Optional export options (title, metadata, base_url,
                trusted_hosts, query)

        Returns:
            ExportResult with DOCX content as bytes, filename, mimetype

        Raises:
            RuntimeError: If pypandoc is missing or Pandoc fails.
        """
        if not PYPANDOC_AVAILABLE:
            raise RuntimeError(
                "DOCX export requires pypandoc. Install with: pip install pypandoc-binary"
            )

        try:
            self._validate_content_size(markdown_content)

            options = options or ExportOptions()

            # 1) Prepend the title (mirrors PDFService behaviour).
            markdown_content = self._prepend_title(
                markdown_content, options.query
            )
            # 2) Scrub the old LDR body footer (defence in depth — older
            #    reports in the DB might still carry it).
            markdown_content = self._scrub_body(markdown_content)

            # Build pandoc args for metadata (sanitized).
            extra_args = []
            if options.title:
                safe_title = self._sanitize_metadata(options.title)
                extra_args.append(f"--metadata=title:{safe_title}")
            if options.metadata:
                if options.metadata.get("author"):
                    safe_author = self._sanitize_metadata(
                        options.metadata["author"]
                    )
                    extra_args.append(f"--metadata=author:{safe_author}")
                if options.metadata.get("date"):
                    safe_date = self._sanitize_metadata(
                        options.metadata["date"]
                    )
                    extra_args.append(f"--metadata=date:{safe_date}")

            # Tell Pandoc where to resolve relative image URLs against.
            # This is the DOCX-path equivalent of WeasyPrint's base_url.
            # ``/images/<research_id>/<filename>`` rewritten by
            # ``images.store.rewrite_markdown`` becomes
            # ``<base_url>images/<research_id>/<filename>`` here, which
            # is exactly the URL the same Flask app serves.
            if options.base_url:
                extra_args.append(
                    f"--resource-path={self._sanitize_metadata(options.base_url)}"
                )

            # Convert in memory: pipe markdown via stdin, capture DOCX
            # bytes from stdout.
            pandoc_path = pypandoc.get_pandoc_path()
            cmd = [pandoc_path, "-f", "markdown", "-t", "docx", "-o", "-"]
            cmd.extend(extra_args)

            result = subprocess.run(
                cmd,
                input=markdown_content.encode("utf-8"),
                capture_output=True,
                check=True,
            )

            docx_bytes = result.stdout

            if not docx_bytes:
                raise RuntimeError(  # noqa: TRY301 — except only adds logging before re-raise
                    "Pandoc conversion failed - no output produced"
                )

            # 3) Post-process: inject the Chinese page-number footer.
            docx_bytes = self._inject_footer_into_docx(docx_bytes)

            filename = self._generate_safe_filename(options.title)

            logger.info(
                f"Generated DOCX in memory, size: {len(docx_bytes)} bytes"
            )

            return ExportResult(
                content=docx_bytes,
                filename=filename,
                mimetype=self.mimetype,
            )

        except subprocess.CalledProcessError as e:
            stderr = (
                e.stderr.decode("utf-8", errors="replace")
                if e.stderr
                else "unknown error"
            )
            logger.exception(f"Pandoc conversion failed: {stderr}")
            raise RuntimeError(f"Pandoc conversion failed: {stderr}") from e
        except Exception:
            logger.exception("Error generating DOCX")
            raise

    # ------------------------------------------------------------------
    # Metadata sanitisation (security: pandoc argument injection)
    # ------------------------------------------------------------------

    def _sanitize_metadata(self, value: str) -> str:
        """Sanitize metadata value to prevent argument injection.

        Removes potential pandoc argument injection patterns from
        user-supplied metadata values. Zero prior direct test coverage.
        """
        if not isinstance(value, str):
            return str(value)

        # Remove leading dashes (prevents --flag injection).
        result = value.lstrip("-")

        # Replace newlines with spaces (prevents multi-line injection).
        # Tabs are preserved — the original ODT sanitizer kept them
        # and downstream consumers may rely on them for tabular data.
        result = result.replace("\n", " ").replace("\r", " ")

        # Collapse any leading multiple-dashes that might remain.
        while result.startswith("--"):
            result = result[1:]

        # Strip all remaining double-dash sequences.
        result = result.replace("--", "")

        return result.strip()
