"""DOCX (Microsoft Word) export service using pypandoc.

This module produces real ``.docx`` files (Office Open XML) via Pandoc,
which natively handles every markdown feature the reports carry —
including the rewritten ``<figure class="ldr-img"><img src="/images/...">``
blocks that ``images.store.rewrite_markdown`` injects. After Pandoc
writes the base DOCX we post-process the zip to add a Chinese
"第X页/共X页" page-number footer via OOXML field codes — Pandoc
itself has no built-in switch for that pattern.
"""

import io
import re
import subprocess
import zipfile
from typing import Optional

from loguru import logger

# pypandoc is optional - used only to locate the bundled pandoc binary
try:
    import pypandoc

    PYPANDOC_AVAILABLE = True
except ImportError:
    pypandoc = None
    PYPANDOC_AVAILABLE = False

from .base import BaseExporter, ExportOptions, ExportResult
from .registry import ExporterRegistry


# OOXML namespaces — used in the footer XML below. Centralised so the
# injected XML stays consistent with what Word/LibreOffice produces.
_W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"


@ExporterRegistry.register
class DOCXExporter(BaseExporter):
    """Service for converting markdown to DOCX (Microsoft Word).

    Uses Pandoc (via pypandoc) for the markdown → DOCX conversion and
    then post-processes the zip to inject:

    * A centred Chinese page-number footer ("第X页/共X页") with PAGE /
      NUMPAGES as real OOXML field codes — Word/LibreOffice updates the
      numbers automatically when the document is opened.

    The exporter threads ``query`` (for the title heading) and
    ``base_url`` (for resolving the rewritten local image routes) the
    same way the PDF path does — so a single research report produces a
    consistent title and embedded images regardless of format.

    The old "Generated by LDR..." body footer is intentionally not
    re-added: the request was to remove that third-party attribution
    from inside the report body. The page-number footer that replaces
    it carries the project link in the same way the PDF footer does.
    """

    @property
    def format_name(self) -> str:
        return "docx"

    @property
    def file_extension(self) -> str:
        return ".docx"

    @property
    def mimetype(self) -> str:
        return "application/vnd.openxmlformats-officedocument.wordprocessingml.document"

    # ------------------------------------------------------------------
    # Title / footer pre-processing
    # ------------------------------------------------------------------

    @staticmethod
    # _prepend_title was replaced by _prepare_markdown below —
    # see comment there for why we no longer inject an H1 into the
    # markdown body (it would produce a duplicate title in Word).


    @staticmethod
    def _prepare_markdown(
        markdown_content: str,
        query: Optional[str],
        base_url: Optional[str],
    ) -> str:
        """Pre-process the markdown before Pandoc.

        The DOCX export path differs from the PDF path in that Pandoc
        cannot easily apply the desired styling (二号 黑体 居中 title,
        body 宋体 五号) via raw markdown — we therefore defer the
        title styling to the DOCX post-process and only touch the
        markdown body for four structural concerns raised by the user:

        1. **No double title**: the report generator already emits
           ``# 目录`` (the first chapter heading) at the top. Prepending
           another H1 here would produce two visible titles in Word.
           Instead, we keep the document body untouched at the top and
           let the post-process inject a single styled title paragraph
           above the body.

        2. **Horizontal rules**: the report adds ``---`` separators
           (e.g. between the TOC and the research summary). The user
           wants no long horizontal lines in the report body, with
           tables exempted. We strip the standalone ``---`` lines but
           leave table separator rows (``|---|---|``) alone.

        3. **TOC formatting**: the report generator emits the TOC
           subsection lines indented with raw spaces, e.g.
           ``   1.1 Sub name | _purpose_``. Pandoc does not treat
           those as nested list items — the asterisks leak through
           and the wrapping is broken. We reformat them to a proper
           nested markdown list so Pandoc's DOCX writer renders a
           clean, multi-level table of contents.

        4. **Image URL rewriting**: the rewritten
           ``/images/<research_id>/<filename>`` routes are
           relative-to-host. Pandoc's ``--resource-path`` does not
           resolve them reliably, so we rewrite each ``src="/images/..."``
           attribute to the absolute URL under the supplied
           ``base_url`` so Pandoc fetches it directly from this same
           Flask app.

        The title text itself (``关于{query}的研究报告``) is **not**
        added to the markdown here — the post-processor injects it
        as a styled paragraph with 二号 黑体 居中 formatting.
        """
        md = markdown_content

        # 1) Convert <figure><img ...>[<figcaption>caption</figcaption>]</figure>
        #    HTML blocks into standard markdown image syntax. The
        #    ``images.store.rewrite_markdown`` produces this HTML
        #    wrapper, but Pandoc's HTML reader does not reliably
        #    extract images from inside <figure> tags — converting
        #    to the bare markdown form routes the image through
        #    Pandoc's well-tested image code path, which then
        #    fetches the (rewritten) URL and embeds the bytes.
        #
        #    The figcaption text is used as the alt-text fallback
        #    when the <img> has no alt attribute (the existing
        #    rewrite_markdown emits the figure+caption this way).
        def _figure_to_md(match):
            block = match.group(0)
            img_m = re.search(r"<img[^>]*?/?>", block)
            if not img_m:
                return block
            tag = img_m.group(0)
            src_m = re.search(r'src="([^"]+)"', tag)
            alt_m = re.search(r'alt="([^"]*)"', tag)
            cap_m = re.search(r"<figcaption[^>]*>(.*?)</figcaption>", block, re.DOTALL)
            width_m = re.search(r'width="([^"]+)"', tag)
            height_m = re.search(r'height="([^"]+)"', tag)
            if not src_m:
                return block
            alt = (alt_m.group(1) if alt_m and alt_m.group(1) else "")
            if not alt and cap_m:
                # Strip any nested HTML inside the caption for clean
                # alt text.
                alt = re.sub(r"<[^>]+>", "", cap_m.group(1)).strip()
            # Forward explicit width/height to Pandoc as link-attribute
            # syntax so the image is embedded at its natural aspect
            # ratio instead of being stretched to fill the page column.
            # Values are kept in CSS pixels (``px``) — Pandoc accepts
            # that unit and the resulting <wp:extent> EMUs come out
            # right.
            dims = ""
            if width_m and height_m:
                dims = (
                    f'{{width="{width_m.group(1)}px" '
                    f'height="{height_m.group(1)}px"}}'
                )
            elif width_m:
                dims = f'{{width="{width_m.group(1)}px"}}'
            elif height_m:
                dims = f'{{height="{height_m.group(1)}px"}}'
            return f"![{alt}]({src_m.group(1)}){dims}"

        md = re.sub(
            r"<figure[^>]*>.*?</figure>",
            _figure_to_md,
            md,
            flags=re.DOTALL,
        )
        # Also handle standalone <img> tags outside any figure wrapper.
        def _standalone_img_to_md(match):
            tag = match.group(0)
            src_m = re.search(r'src="([^"]+)"', tag)
            alt_m = re.search(r'alt="([^"]*)"', tag)
            if not src_m:
                return tag
            return f"![{alt_m.group(1) if alt_m else ''}]({src_m.group(1)})"
        md = re.sub(r"<img[^>]*?/?>", _standalone_img_to_md, md)

        # 2) Rewrite relative ``/images/...`` URLs in markdown image
        #    syntax (``(.../images/foo.png)``) to absolute under
        #    ``base_url``. Done after step 1 so we catch the markdown
        #    form too, not just raw HTML attributes. Already-absolute
        #    ``http://``/``https://``/``data:`` URLs pass through
        #    unchanged.
        if base_url:
            abs_base = base_url.rstrip("/") + "/"
            md = re.sub(
                r"\((/images/[^)\s]+)\)",
                lambda m: f"({abs_base}{m.group(1).lstrip('/')})",
                md,
            )
            # Also rewrite HTML attribute form (covers any leftover
            # <img src="..."> that the previous step missed).
            md = re.sub(
                r'src="/(images/[^"]+)"',
                lambda m: f'src="{abs_base}{m.group(1)}"',
                md,
            )

        # 3) Strip standalone ``---`` rules. A horizontal rule in
        #    CommonMark is a line containing only ``---`` (optionally
        #    with up to 3 spaces of indent). Table separator rows
        #    start with ``|`` so they are unaffected.
        md = re.sub(r"(?m)^[ \t]{0,3}---[ \t]*\n", "", md)

        # 4) Reformat the TOC into a proper nested bullet list. The
        #    report generator emits:
        #        1. **Section 1**
        #           1.1 Sub one | _purpose one_
        #        2. **Section 2**
        #    Pandoc's markdown reader does NOT treat the three-space
        #    indent on the subsection line as a nested list item, so
        #    the asterisks leak through and the line wrap is broken.
        #    We rewrite the top-level numbered items to bare bullets
        #    (``-``) and the subsection lines to two-space-indented
        #    nested bullets so Pandoc's DOCX writer renders a clean
        #    multi-level TOC.
        md = re.sub(
            r"(?m)^(?P<num>\d+)\.\s+(?P<body>\*\*.+\*\*)\s*$",
            lambda m: f"- {m.group('body')}",
            md,
        )
        md = re.sub(
            r"(?m)^(?P<indent>[ ]{3,3})\d+\.\d+\s+(?P<body>.+?)\r?$",
            # Strip a trailing ``\r`` first — Windows CRLF reports
            # would otherwise carry it through into the bullet body
            # and break Pandoc's parser. The ``(?P<body>.+?)`` is
            # non-greedy so we don't accidentally eat the whole file.
            lambda m: f"  - {m.group('body').rstrip(chr(13)).replace('|', ' — ')}",
            md,
        )

        # 5) Demote every body H1 to H2 (and every H2 to H3) so the
        #    only H1 in the rendered document is the user-requested
        #    ``关于X的研究报告`` title that the post-processor injects
        #    at the very top of <w:body>. The report generator emits
        #    ``# 目录`` and ``# 研究摘要`` as H1s, and LLM-generated
        #    chapter content sometimes opens with a ``# <topic>`` H1
        #    too — all of these would otherwise render as a second
        #    "title" in Word next to the injected one. Demoting them
        #    keeps the visual hierarchy (everything is a sub-heading
        #    of the report title) without losing the heading
        #    distinction in the document.
        md = re.sub(
            r"(?m)^#### (.+)$", r"##### \1", md,
        )
        md = re.sub(
            r"(?m)^### (.+)$", r"#### \1", md,
        )
        md = re.sub(
            r"(?m)^## (.+)$", r"### \1", md,
        )
        md = re.sub(
            r"(?m)^# (.+)$", r"## \1", md,
        )

        return md

    @staticmethod
    def _build_title_paragraph_xml(query: str) -> str:
        """Return an OOXML ``<w:p>`` carrying the title line.

        The post-processor injects this paragraph at the very top of
        ``<w:body>``. The styling is the user-specified combination:

        * 字号: 二号 = 22pt = 44 half-points
        * 字体: 黑体 family stack (SimHei / Heiti SC / Noto Sans CJK SC)
        * 加粗: bold
        * 对齐: 居中 (centered)
        * 颜色: 黑色 (default — no ``w:color`` override)

        The text is the full ``关于{query}的研究报告`` template — not
        just the raw query. The query string is HTML-escaped so a
        malformed query (e.g. containing ``<``) cannot break the XML.
        """
        title_text = f"关于{query}的研究报告"
        safe_text = (
            title_text
            .replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
        )
        return (
            "<w:p>"
            "<w:pPr>"
            '<w:jc w:val="center"/>'
            '<w:rPr>'
            '<w:rFonts w:ascii="SimHei" w:hAnsi="SimHei" '
            'w:eastAsia="SimHei" w:cs="Heiti SC" w:hint="eastAsia"/>'
            '<w:b/>'
            '<w:bCs/>'
            '<w:sz w:val="44"/>'
            '<w:szCs w:val="44"/>'
            "</w:rPr>"
            "</w:pPr>"
            "<w:r>"
            "<w:rPr>"
            '<w:rFonts w:ascii="SimHei" w:hAnsi="SimHei" '
            'w:eastAsia="SimHei" w:cs="Heiti SC" w:hint="eastAsia"/>'
            "<w:b/>"
            "<w:bCs/>"
            '<w:sz w:val="44"/>'
            '<w:szCs w:val="44"/>'
            "</w:rPr>"
            f"<w:t xml:space=\"preserve\">{safe_text}</w:t>"
            "</w:r>"
            "</w:p>"
        )

    @staticmethod
    def _scrub_body(markdown_content: str) -> str:
        """Strip the old LDR attribution footer from the body, if any.

        ``ODTExporter._add_footer`` used to append ``Generated by LDR...``
        to every export. The request was to remove that text from the
        report body. We scrub defensively so that any historical
        markdown already containing the footer still comes out clean.
        """
        # Strip the "Generated by [LDR ...]" attribution paragraph,
        # whether or not it is wrapped in italic ``*...*`` markers, and
        # drop the ``---`` horizontal rule that may have preceded it.
        # Match across the full paragraph so we leave no stray blank
        # lines behind.
        pattern = re.compile(
            r"(?:\s*---\s*\n)?\s*\*?Generated by "
            r"\[LDR[^\]]*\][^\n]*\*?\s*$",
            re.MULTILINE,
        )
        return pattern.sub("", markdown_content).rstrip() + "\n"


    @staticmethod
    def _set_default_body_font(names_to_data: dict) -> dict:
        """Patch ``word/styles.xml`` so unstyled body text uses 宋体 五号.

        Replaces / inserts the ``<w:docDefaults><w:rPrDefault><w:rPr>``
        block with a SimSun 10.5pt run properties default. Headings are
        left untouched.
        """
        styles_path = "word/styles.xml"
        if styles_path not in names_to_data:
            # Pandoc usually emits a styles.xml; bail if not.
            return names_to_data
        styles_xml = names_to_data[styles_path].decode("utf-8")

        new_rpr = (
            "<w:rPr>"
            '<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="21"/>'   # 10.5pt = 21 half-points (五号)
            '<w:szCs w:val="21"/>'
            "</w:rPr>"
        )
        if "<w:rPrDefault>" in styles_xml:
            styles_xml = re.sub(
                r"<w:rPrDefault>.*?</w:rPrDefault>",
                f"<w:rPrDefault>{new_rpr}</w:rPrDefault>",
                styles_xml,
                count=1,
                flags=re.DOTALL,
            )
        else:
            # Insert as a child of docDefaults.
            if "<w:docDefaults>" in styles_xml:
                styles_xml = re.sub(
                    r"(<w:docDefaults[^>]*>)",
                    lambda m: m.group(1) + f"<w:rPrDefault>{new_rpr}</w:rPrDefault>",
                    styles_xml,
                    count=1,
                )
            else:
                # No docDefaults — create one near the top.
                styles_xml = re.sub(
                    r"(<w:styles[^>]*>)",
                    lambda m: (
                        m.group(1)
                        + f'<w:docDefaults><w:rPrDefault>{new_rpr}</w:rPrDefault></w:docDefaults>'
                    ),
                    styles_xml,
                    count=1,
                )
        names_to_data[styles_path] = styles_xml.encode("utf-8")
        return names_to_data

    @staticmethod
    def _strip_query_heading_style(
        names_to_data: dict, query: Optional[str]
    ) -> dict:
        """Delete any body paragraph whose visible text **equals** the
        query AND whose pStyle references a heading.

        LLM-generated report content sometimes opens a chapter with
        ``# <query>`` (the LLM reuses the research question as the
        chapter heading). After the H1→H2 demote in
        ``_prepare_markdown`` this lands in the body as an H2, which
        Word still renders as a prominent heading — the user sees
        it as a "second title" alongside the injected
        ``关于X的研究报告``.

        The fix: for every ``<w:p>`` in ``word/document.xml`` that has
        a ``<w:pStyle>`` referencing a heading style (``Heading1``
        through ``Heading9``, ``Title``), check if the visible text
        equals the query (whitespace-stripped). If so, delete the
        *entire* paragraph so the duplicate title text is gone from
        the body. Legitimate section headings that merely *contain*
        the query as a substring of a longer title (e.g.
        "量子计算的发展历程" with query "量子计算") are preserved
        because the match is exact.

        The match is whitespace-stripped on both sides so a
        paragraph with leading/trailing spaces inside its ``<w:t>``
        still matches the query.
        """
        if not query:
            return names_to_data
        doc_path = "word/document.xml"
        if doc_path not in names_to_data:
            return names_to_data
        doc_xml = names_to_data[doc_path].decode("utf-8")
        # Heading style IDs Pandoc emits. Match any of these as the
        # paragraph's pStyle.
        heading_styles = (
            "Heading1", "Heading2", "Heading3", "Heading4",
            "Heading5", "Heading6", "Heading7", "Heading8",
            "Heading9", "Title",
        )
        # Build a regex that matches a single <w:p>...</w:p> block.
        # Inside, check: (a) has a pStyle whose val is one of
        # heading_styles, AND (b) the visible text contains the query.
        # If both, drop the pStyle child of pPr.
        heading_alt = "|".join(heading_styles)

        def patch_para(match: "re.Match[str]") -> str:
            block = match.group(0)
            # Only touch paragraphs that carry a heading pStyle.
            style_m = re.search(
                rf'<w:pStyle\s+w:val="({heading_alt})"\s*/>',
                block,
            )
            if not style_m:
                return block
            # The visible text of a <w:p> is the concatenation of its
            # <w:t> children. We require an *exact* match against the
            # query (whitespace-stripped) so that legitimate section
            # headings like "量子计算的发展历程" — which merely
            # *contain* the query "量子计算" as a substring — are
            # not wiped out. Substring-match here was the bug the
            # review caught.
            texts = re.findall(r"<w:t[^>]*>([^<]*)</w:t>", block)
            visible = "".join(texts).strip()
            if visible != query.strip():
                return block
            # Delete the entire paragraph — the user wants the
            # duplicate-title text gone from the body, not just
            # demoted to a regular paragraph. Returning "" makes
            # re.sub erase the matched <w:p>...</w:p> block.
            return ""

        doc_xml = re.sub(
            r"<w:p\b[^>]*>.*?</w:p>",
            patch_para,
            doc_xml,
            flags=re.DOTALL,
        )
        names_to_data[doc_path] = doc_xml.encode("utf-8")
        return names_to_data

    @staticmethod
    def _patch_styles_xml_kaiti_headings(
        names_to_data: dict,
        headings: tuple = ("Heading1", "Heading2", "Heading3",
                          "Heading4", "Heading5", "Heading6", "Title"),
    ) -> dict:
        """Replace the font family on every heading style with 楷体.

        The user asked for report section titles to render in 楷体
        (regular-script Chinese typeface). Pandoc emits the heading
        styles in ``word/styles.xml`` with theme-based rFonts
        (``w:asciiTheme="majorHAnsi"`` etc.) which render with the
        Word/LibreOffice theme default — not 楷体. We rewrite each
        ``HeadingN`` rPr rFonts to an explicit 楷体 family stack
        (SimKai → KaiTi → STKaiti → Noto Serif CJK → serif).

        Heading *sizes* are deliberately left untouched — only the
        font family is changed. Body font (SimSun 五号) is set by
        ``_set_default_body_font`` and is independent of this patcher.
        """
        styles_path = "word/styles.xml"
        if styles_path not in names_to_data:
            return names_to_data
        styles_xml = names_to_data[styles_path].decode("utf-8")

        # 楷体 family stack — SimKai (Windows) → KaiTi (macOS) →
        # STKaiti (Traditional) → Noto Serif CJK TC (Linux). The
        # w:cs="KaiTi" hint steers Word's complex-script fallback
        # the same way; w:hint="eastAsia" tells the renderer to apply
        # the eastAsia name to CJK characters.
        kaiti_rfonts = (
            'w:ascii="KaiTi" '
            'w:hAnsi="KaiTi" '
            'w:eastAsia="KaiTi" '
            'w:cs="KaiTi" '
            'w:hint="eastAsia"'
        )

        for h in headings:
            # Find the Heading style block. Multiline match.
            pat = re.compile(
                rf'(<w:style[^>]*w:styleId="{h}".*?</w:style>)',
                re.DOTALL,
            )
            m = pat.search(styles_xml)
            if not m:
                # Pandoc did not emit a style block for this heading
                # level — nothing to patch.
                continue
            original_block = m.group(1)
            block = original_block
            # Ensure rPr exists so we can attach rFonts + colour. If
            # the style has none yet, create one just before </w:style>.
            if "<w:rPr>" not in block:
                block = block.replace(
                    "</w:style>",
                    "<w:rPr></w:rPr></w:style>",
                    1,
                )
            # Set 楷体 (KaiTi) font — replaces any existing rFonts
            # (theme-based or otherwise) so Word/LibreOffice does not
            # fall back to a Latin theme font for CJK characters.
            if "<w:rFonts" in block:
                block = re.sub(
                    r"<w:rFonts[^/]*/>",
                    f'<w:rFonts {kaiti_rfonts}/>',
                    block,
                    count=1,
                )
            else:
                block = block.replace(
                    "<w:rPr>",
                    f"<w:rPr><w:rFonts {kaiti_rfonts}/>",
                    1,
                )
            # Force the heading text colour to pure black. Pandoc's
            # default DOCX template ships headings with a tinted dark
            # blue (``2E74B5``) which the user does not want.
            if re.search(r"<w:color\s", block):
                block = re.sub(
                    r'<w:color\s[^/]*/>',
                    '<w:color w:val="000000"/>',
                    block,
                    count=1,
                )
            else:
                block = block.replace(
                    "<w:rPr>",
                    '<w:rPr><w:color w:val="000000"/>',
                    1,
                )
            styles_xml = styles_xml.replace(original_block, block, 1)

        names_to_data[styles_path] = styles_xml.encode("utf-8")
        return names_to_data

    @staticmethod
    def _title_already_present(doc_xml: str, title_para_xml: str) -> bool:
        """Return True if a paragraph carrying the same title text is
        already in the body — prevents duplicate-injection on retries."""
        m = re.search(r"<w:t[^>]*>([^<]+)</w:t>", title_para_xml)
        if not m:
            return False
        return m.group(1) in doc_xml

    # ------------------------------------------------------------------
    # Page-number footer XML
    # ------------------------------------------------------------------

    @staticmethod
    def _build_footer_xml() -> str:
        """Return the inner XML of word/footer1.xml carrying the
        Chinese page-number footer. Uses real OOXML field codes for
        PAGE / NUMPAGES so Word updates them on open.

        Mirrors the PDF path's "第X页/共X页" format and font stack
        (宋体 family, 五号 ≈ 9pt) so DOCX and PDF exports look
        consistent. Centred.
        """
        # We embed the field codes directly (fldSimple) so Word treats
        # them as live PAGE / NUMPAGES fields rather than literal text.
        return (
            '<w:p>'
            '<w:pPr>'
            '<w:jc w:val="center"/>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'   # 9pt = 18 half-points (五号)
            '<w:szCs w:val="18"/>'
            ''
            '</w:rPr>'
            '</w:pPr>'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            ''
            '</w:rPr>'
            '<w:t xml:space="preserve">第</w:t>'
            '</w:r>'
            '<w:fldSimple w:instr="PAGE \\* MERGEFORMAT">'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            ''
            '</w:rPr>'
            '<w:t>1</w:t>'
            '</w:r>'
            '</w:fldSimple>'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            ''
            '</w:rPr>'
            '<w:t xml:space="preserve">页/共</w:t>'
            '</w:r>'
            '<w:fldSimple w:instr="NUMPAGES \\* MERGEFORMAT">'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            ''
            '</w:rPr>'
            '<w:t>1</w:t>'
            '</w:r>'
            '</w:fldSimple>'
            '<w:r>'
            '<w:rPr>'
            f'<w:rFonts w:ascii="SimSun" w:hAnsi="SimSun" w:eastAsia="SimSun" w:cs="SimSun"/>'
            '<w:sz w:val="18"/>'
            '<w:szCs w:val="18"/>'
            ''
            '</w:rPr>'
            '<w:t xml:space="preserve">页</w:t>'
            '</w:r>'
            '</w:p>'
        )

    @staticmethod
    def _wrap_footer(footer_inner_xml: str) -> str:
        """Wrap the footer inner XML in the required ``<w:ftr>`` root."""
        return (
            '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
            f'<w:ftr xmlns:w="{_W_NS}">'
            f'{footer_inner_xml}'
            '</w:ftr>'
        )

    @classmethod
    def _inject_footer_into_docx(
        cls, docx_bytes: bytes, query: Optional[str] = None
    ) -> bytes:
        """Return a copy of the DOCX with the post-processing done.

        Three concerns the user asked us to address live here, because
        Pandoc cannot express them through raw markdown:

          1. The Chinese page-number footer (``第N页/共M页``) is
             injected as ``word/footer1.xml`` with real OOXML PAGE /
             NUMPAGES field codes — Word/LibreOffice update the
             numbers on open.
          2. The report title (``关于{query}的研究报告``) is injected
             as a styled ``<w:p>`` at the very top of ``<w:body>``
             so it is the *only* title (the report itself starts with
             ``# 目录`` and would otherwise produce two visible titles).
             二号 (22pt) 黑体, bold, centred, black.
          3. The default body font/size in ``word/styles.xml`` is set
             to 宋体 (SimSun) 五号 (10.5pt = 21 half-points), and
             ``w:themeFontLang``/``w:rPrDefault`` are wired so Word
             uses this for unstyled body text. Heading styles are
             left untouched so chapter heading sizes are unchanged.

        Algorithm:
          1. Unzip the DOCX into memory.
          2. If ``word/footer1.xml`` doesn't exist, create it with
             our page-number XML.
          3. Ensure ``word/_rels/document.xml.rels`` carries a
             relationship to ``footer1.xml`` with a stable Id.
          4. Ensure ``[Content_Types].xml`` declares the footer part.
          5. Ensure each ``<w:sectPr>`` in ``word/document.xml``
             references the footer relationship.
          6. Inject the title paragraph at the very top of
             ``<w:body>`` (only if ``query`` is provided).
          7. Patch ``word/styles.xml`` so the body default is 宋体 五号.

        Idempotent: re-running on an already-patched DOCX keeps the
        existing footer instead of duplicating it.
        """
        if not docx_bytes:
            return docx_bytes

        footer_xml = cls._wrap_footer(cls._build_footer_xml())
        title_para_xml = (
            cls._build_title_paragraph_xml(query) if query else None
        )
        footer_rid = "rIdLdrFooter"

        # Read everything into memory up front — DOCX files are small.
        src_zip = zipfile.ZipFile(io.BytesIO(docx_bytes), "r")
        names_to_data = {name: src_zip.read(name) for name in src_zip.namelist()}
        src_zip.close()

        # 1) Write footer1.xml (overwrite if present, create if not).
        names_to_data["word/footer1.xml"] = footer_xml.encode("utf-8")

        # 2) Update word/_rels/document.xml.rels so the footer part is
        #    discoverable by document.xml.
        rels_path = "word/_rels/document.xml.rels"
        rels_xml = names_to_data.get(rels_path, b"").decode("utf-8") if rels_path in names_to_data else ""
        if rels_xml and 'Target="footer1.xml"' not in rels_xml:
            # Insert the footer relationship before </Relationships>.
            new_rel = (
                f'<Relationship Id="{footer_rid}" '
                'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" '
                'Target="footer1.xml"/>'
            )
            rels_xml = rels_xml.replace(
                "</Relationships>", new_rel + "</Relationships>", 1
            )
            names_to_data[rels_path] = rels_xml.encode("utf-8")
        elif not rels_xml:
            # No rels file at all — minimal valid one.
            rels_xml = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">'
                + f'<Relationship Id="{footer_rid}" '
                'Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/footer" '
                'Target="footer1.xml"/>'
                + "</Relationships>"
            )
            names_to_data[rels_path] = rels_xml.encode("utf-8")

        # 3) Update [Content_Types].xml so the footer part is declared.
        ct_path = "[Content_Types].xml"
        ct_xml = (
            names_to_data[ct_path].decode("utf-8")
            if ct_path in names_to_data
            else ""
        )
        if ct_xml and 'PartName="/word/footer1.xml"' not in ct_xml:
            override = (
                '<Override PartName="/word/footer1.xml" '
                'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>'
            )
            ct_xml = ct_xml.replace("</Types>", override + "</Types>", 1)
            names_to_data[ct_path] = ct_xml.encode("utf-8")
        elif not ct_xml:
            ct_xml = (
                '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>'
                '<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">'
                '<Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/>'
                '<Default Extension="xml" ContentType="application/xml"/>'
                '<Override PartName="/word/document.xml" '
                'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/>'
                '<Override PartName="/word/footer1.xml" '
                'ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.footer+xml"/>'
                '</Types>'
            )
            names_to_data[ct_path] = ct_xml.encode("utf-8")

        # 4) Update every <w:sectPr> in word/document.xml to reference
        #    our footer relationship. Word renders the footer on every
        #    page in the section.
        doc_path = "word/document.xml"
        doc_xml = (
            names_to_data[doc_path].decode("utf-8")
            if doc_path in names_to_data
            else ""
        )
        if doc_xml and f'r:id="{footer_rid}"' not in doc_xml:
            # Find every <w:sectPr ...> ... </w:sectPr> block and
            # ensure it carries a <w:footerReference w:type="default"
            # r:id="..."/> child. If the block already has one, replace
            # the r:id. Otherwise insert one as the first child.
            def patch_sectpr(match: "re.Match[str]") -> str:
                block = match.group(0)
                if "footerReference" in block and f'r:id="{footer_rid}"' in block:
                    return block
                new_ref = (
                    f'<w:footerReference w:type="default" r:id="{footer_rid}"/>'
                )
                if "footerReference" in block:
                    # Replace the first existing footerReference's r:id.
                    return re.sub(
                        r'<w:footerReference[^/]*r:id="[^"]*"[^/]*/>',
                        new_ref,
                        block,
                        count=1,
                    )
                # Insert as the first child of sectPr.
                # Find the opening tag's closing >.
                open_tag_end = block.find(">") + 1
                return block[:open_tag_end] + new_ref + block[open_tag_end:]

            doc_xml = re.sub(
                r"<w:sectPr\b[^>]*>.*?</w:sectPr>",
                patch_sectpr,
                doc_xml,
                flags=re.DOTALL,
            )
            # Self-closing <w:sectPr .../> form (Pandoc occasionally emits
            # this for the final section).
            def patch_selfclosing_sectpr(match: "re.Match[str]") -> str:
                attrs = match.group(1)
                return (
                    f"<w:sectPr{attrs}>"
                    f'<w:footerReference w:type="default" r:id="{footer_rid}"/>'
                    "</w:sectPr>"
                )
            doc_xml = re.sub(
                r"<w:sectPr\b([^>]*)/>",
                patch_selfclosing_sectpr,
                doc_xml,
            )
            names_to_data[doc_path] = doc_xml.encode("utf-8")

        # 6) Inject the title paragraph at the very top of <w:body>.
        if title_para_xml and doc_path in names_to_data:
            doc_xml = names_to_data[doc_path].decode("utf-8")
            # Insert the title paragraph right after <w:body> opens,
            # before any existing body content. Idempotent: skip if a
            # title with the same text is already present.
            if not cls._title_already_present(doc_xml, title_para_xml):
                doc_xml = re.sub(
                    r"(<w:body[^>]*>)",
                    lambda m: m.group(1) + title_para_xml,
                    doc_xml,
                    count=1,
                )
                names_to_data[doc_path] = doc_xml.encode("utf-8")

        # 7) Patch word/styles.xml: body default 宋体 五号, heading
        #    styles 楷体 (sizes unchanged). Body font and heading
        #    font are independent patches — order doesn't matter
        #    because each touches a disjoint rPr block.
        names_to_data = cls._set_default_body_font(names_to_data)
        names_to_data = cls._patch_styles_xml_kaiti_headings(names_to_data)

        # 8) Strip the heading style from any body paragraph that
        #    contains the query text. LLM chapters often open with
        #    ``# <query>`` which would otherwise render as a second
        #    "title" next to the user-requested title injected in
        #    step 6. We drop just the pStyle so the heading text
        #    stays in the document but renders as ordinary body text.
        if query:
            names_to_data = cls._strip_query_heading_style(
                names_to_data, query
            )

        # Write the new zip back out.
        out_buf = io.BytesIO()
        with zipfile.ZipFile(out_buf, "w", zipfile.ZIP_DEFLATED) as dst_zip:
            for name, data in names_to_data.items():
                dst_zip.writestr(name, data)
        return out_buf.getvalue()

    # ------------------------------------------------------------------
    # Markdown → DOCX
    # ------------------------------------------------------------------

    def export(
        self,
        markdown_content: str,
        options: Optional[ExportOptions] = None,
    ) -> ExportResult:
        """Convert markdown content to DOCX.

        Flow:
          1. Prepend the "关于{query}的研究报告" title (if query given).
          2. Scrub the old "Generated by LDR..." body footer.
          3. Run Pandoc markdown → DOCX, with ``--resource-path`` set to
             the request's base_url so the rewritten
             ``/images/<research_id>/<filename>`` routes resolve.
          4. Post-process the resulting DOCX zip to inject the
             Chinese page-number footer.

        Args:
            markdown_content: The markdown text to convert
            options: Optional export options (title, metadata, base_url,
                trusted_hosts, query)

        Returns:
            ExportResult with DOCX content as bytes, filename, mimetype

        Raises:
            RuntimeError: If pypandoc is missing or Pandoc fails.
        """
        if not PYPANDOC_AVAILABLE:
            raise RuntimeError(
                "DOCX export requires pypandoc. Install with: pip install pypandoc-binary"
            )

        try:
            self._validate_content_size(markdown_content)

            options = options or ExportOptions()

            # 1) Pre-process: scrub horizontal rules, fix the TOC
            #    formatting, rewrite relative image URLs to absolute
            #    under base_url. The title text itself is NOT added
            #    here — it is injected as a styled OOXML paragraph by
            #    the post-processor (a markdown H1 would produce a
            #    duplicate title alongside the report's existing
            #    ``# 目录`` first heading).
            markdown_content = self._prepare_markdown(
                markdown_content, options.query, options.base_url
            )
            # 2) Scrub the old LDR body footer (defence in depth —
            #    older reports in the DB might still carry it).
            markdown_content = self._scrub_body(markdown_content)

            # Build pandoc args for metadata (sanitized).
            extra_args = []
            if options.title:
                safe_title = self._sanitize_metadata(options.title)
                extra_args.append(f"--metadata=title:{safe_title}")
            if options.metadata:
                if options.metadata.get("author"):
                    safe_author = self._sanitize_metadata(
                        options.metadata["author"]
                    )
                    extra_args.append(f"--metadata=author:{safe_author}")
                if options.metadata.get("date"):
                    safe_date = self._sanitize_metadata(
                        options.metadata["date"]
                    )
                    extra_args.append(f"--metadata=date:{safe_date}")

            # Tell Pandoc where to resolve relative image URLs against.
            # This is the DOCX-path equivalent of WeasyPrint's base_url.
            # ``/images/<research_id>/<filename>`` rewritten by
            # ``images.store.rewrite_markdown`` becomes
            # ``<base_url>images/<research_id>/<filename>`` here, which
            # is exactly the URL the same Flask app serves.
            if options.base_url:
                extra_args.append(
                    f"--resource-path={self._sanitize_metadata(options.base_url)}"
                )

            # Convert in memory: pipe markdown via stdin, capture DOCX
            # bytes from stdout.
            pandoc_path = pypandoc.get_pandoc_path()
            cmd = [pandoc_path, "-f", "markdown", "-t", "docx", "-o", "-"]
            cmd.extend(extra_args)

            # 30 s timeout matches the PDFService guidance. A slow
            # network image fetch inside the DOCX post-process path
            # (``--resource-path`` triggers HTTP GETs for every image
            # reference) can otherwise pin the export worker
            # indefinitely; the user gets a clear PandocTimeout
            # error instead of a hang.
            result = subprocess.run(
                cmd,
                input=markdown_content.encode("utf-8"),
                capture_output=True,
                check=True,
                timeout=30,
            )

            docx_bytes = result.stdout

            if not docx_bytes:
                raise RuntimeError(  # noqa: TRY301 — except only adds logging before re-raise
                    "Pandoc conversion failed - no output produced"
                )

            # 3) Post-process: inject the Chinese page-number footer.
            docx_bytes = self._inject_footer_into_docx(docx_bytes, query=options.query)

            filename = self._generate_safe_filename(options.title)

            logger.info(
                f"Generated DOCX in memory, size: {len(docx_bytes)} bytes"
            )

            return ExportResult(
                content=docx_bytes,
                filename=filename,
                mimetype=self.mimetype,
            )

        except subprocess.CalledProcessError as e:
            stderr = (
                e.stderr.decode("utf-8", errors="replace")
                if e.stderr
                else "unknown error"
            )
            logger.exception(f"Pandoc conversion failed: {stderr}")
            raise RuntimeError(f"Pandoc conversion failed: {stderr}") from e
        except Exception:
            logger.exception("Error generating DOCX")
            raise

    # ------------------------------------------------------------------
    # Metadata sanitisation (security: pandoc argument injection)
    # ------------------------------------------------------------------

    def _sanitize_metadata(self, value: str) -> str:
        """Sanitize metadata value to prevent argument injection.

        Removes potential pandoc argument injection patterns from
        user-supplied metadata values. Zero prior direct test coverage.
        """
        if not isinstance(value, str):
            return str(value)

        # Remove leading dashes (prevents --flag injection).
        result = value.lstrip("-")

        # Replace newlines with spaces (prevents multi-line injection).
        # Tabs are preserved — the original ODT sanitizer kept them
        # and downstream consumers may rely on them for tabular data.
        result = result.replace("\n", " ").replace("\r", " ")

        # Collapse any leading multiple-dashes that might remain.
        while result.startswith("--"):
            result = result[1:]

        # Strip all remaining double-dash sequences.
        result = result.replace("--", "")

        return result.strip()
